variables:
  System.Debug: true  # Enables detailed logging for troubleshooting
  nodeVersion: '16.x'
  buildArtifactName: 'nodejs-app'

stages:
  - stage: Build
    jobs:
      - job: NodeJsBuild
        steps:
          - task: UseNode@1
            inputs:
              versionSpec: $(nodeVersion)
              checkLatest: true

          - script: |
              set -x
              npm install
            displayName: 'Install dependencies'

          - script: |
              set -x
              npm test
            displayName: 'Run tests'

          - script: |
              set -x
              npm run build
            displayName: 'Build project'
